[workspace]
resolver = "2"
members = ["crates/excel-unprotect", "crates/image-transformer", "crates/vol-level-lock"]

[workspace.package]
authors = ["dannycreations"]
edition = "2021"
license = "GPL"
repository = "https://github.com/dannycreations/Kani"

[workspace.dependencies]
anyhow = "1.0.103"
assert_cmd = "2.2.2"
clap = { version = "4.6.1", features = ["derive"] }
ctrlc = "3.5.2"
indicatif = { version = "0.18.6", features = ["rayon"] }
predicates = "3.1.4"
rayon = "1.12.0"
tempfile = "3.27.0"
thiserror = "2.0.18"
walkdir = "=2.5.0"

[profile.dev]
codegen-units = 16
debug = 1
incremental = true

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = false
lto = true
opt-level = "z"
panic = "abort"
split-debuginfo = "packed"
