[package]
name = "image-transformer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
image = "0.25.10"
indicatif = { workspace = true, features = ["rayon"] }
oxipng = "10.2.1"
rayon.workspace = true
thiserror.workspace = true
walkdir.workspace = true
